### ISSUE TITLE
Binary search 

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/data-structure-#2]
I want binary search code

**Comment by Kraken-ops** [comment]
I want to contribute to this issue.

**Comment by utkr07** [comment]
Hello @hariom20singh .
Can you please assign this to me? I'll write an optimum code for Binary Search. Thank you.

**Comment by deb3121** [comment]
I want to contribute to this issue.

**Comment by Tusharsolanki077** [comment]
Hey @hariom20singh Please assign this task to me . I will provide a recursive method of binary search.
