### ISSUE TITLE
complete linked list

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/data-structure-#3]
want code of complete linked list like insertion , deletion , and other operations

**Comment by anujverma-eng** [comment]
@hariom20singh Kindly check the hacktoberfest T&C, you have not added CONTRIBUTING.md.md file, neither u created a better Readme.md
Review the T&C and then add the label hacktoberfest [ violating the policy will not give u or the contributor a benefit]

![image](https://user-images.githubusercontent.com/66346190/194512737-3bf481f6-0aa2-47f0-8839-f05c6ade4348.png)

**Comment by hariom20singh** [comment]
ok I check...
Thank you @anujverma-eng

**Comment by Kraken-ops** [comment]
I want to contribute to this issue.

**Comment by hariom20singh** [comment]
I assigned @Kraken-ops
