### ISSUE TITLE
Dsa for  beginner

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/data-structure-#32]

**Comment by mohithgupta** [comment]
Can I just make a pull request with anything related to DSA? Or do you have to assign me something?

**Comment by jaskeerat2709** [comment]
i want to contribute

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by pallavi2031** [comment]
can you assign this issue I want to contribute.

**Comment by Shekhawatt** [comment]
Please assign me this issue
