### ISSUE TITLE
 algorithm for beginner

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/data-structure-#33]

**Comment by Aryaman047** [comment]
Please assign this issue to me sir

**Comment by RKSingh5** [comment]
please assign this to me

**Comment by hariom20singh** [comment]
make sure your code is unique

**Comment by RKSingh5** [comment]
Added change from infix to postfix expression using stack in C 
If useful please merge the pr #36

**Comment by deepesh85b** [comment]
@hariom20singh 
Please assign this to me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue?

**Comment by Shekhawatt** [comment]
Please assign me this issue
