### ISSUE TITLE
submit code for hacktoberfest

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/data-structure-#41]

**Comment by aashish-1904** [comment]
Hello, i would like to do this task

**Comment by s4shantanu** [comment]
Hey @hariom20singh  Please approve my PR I Push with Java solution

**Comment by aashish-1904** [comment]
Hello, i would like to contribute to this repository

**Comment by Akshat-706** [comment]
@hariom20singh pls assign it to me

**Comment by jaskeerat2709** [comment]
Hello, i would like to contribute to this repository
